//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessLDAP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long Id { get; set; }
        public long UserID { get; set; }
        public System.DateTime LoggedIn { get; set; }
        public System.Guid TokenID { get; set; }
    
        public virtual User User { get; set; }
    }
}
